const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, codeBlock, ButtonStyle, ChannelType } = require("discord.js");
const api = require("../../../api/index");
const {cache} = require("../../commands/archive");

const config = require("../../../config.json");

const listener = {
    name: 'archiveModalManager',
    /**
     * Verifies a button press should be sent to this listener
     * @param {ModalSubmitInteraction} interaction 
     */
    verify(interaction) {
        return interaction.customId === "archive-create";
    },
    /**
     * Listener for a button press
     * @param {ModalSubmitInteraction} interaction 
     */
    listener (interaction) {
        if (interaction.customId === "archive-create") {
            api.Discord.getUserById(interaction.member.id).then(async user => {
                if (user.identity?.id) {
                    const offense = interaction.fields.getTextInputValue("offense");
                    const description = interaction.fields.getTextInputValue("description");
                    
                    if (cache.hasOwnProperty(user.identity.id)) {
                        cache[user.identity.id].offense = offense;
                        cache[user.identity.id].description = description;

                        let entry = cache[user.identity.id];

                        let resolvable = "";
                        let unresolvable = "";

                        for (let t = 0; t < entry.twitch.length; t++) {
                            let name = entry.twitch[t];
                            try {
                                let accounts = await api.Twitch.getUserByName(name, true);

                                accounts.forEach(account => {
                                    resolvable += `\nTwitch Account: ${account.display_name} (${account.id})`;
                                });
                            } catch (err) {
                                unresolvable += "\nTwitch Name: " + name;
                            }
                        }
                        
                        for (let d = 0; d < entry.discord.length; d++) {
                            let id = entry.discord[d];
                            try {
                                let account = await api.Discord.getUserById(id, false, true);

                                resolvable += `\nDiscord Account: ${account.name}#${account.discriminator} (${account.id})`;
                            } catch (err) {
                                unresolvable += "\nDiscord ID: " + id;
                            }
                        }

                        for (let i = 0; i < entry.identity.length; i++) {
                            let id = entry.identity[i];
                            try {
                                let account = await api.getFullIdentity(id);

                                resolvable += `\nIdentity: ${account.name} (${account.id}) / Accounts [T:${account.twitchAccounts.length},D:${account.discordAccounts.length}]`;
                            } catch (err) {
                                unresolvable += "\nIdentity ID: " + id + " (unresolved identities will not be added)";
                            }
                        }

                        entry.channel.threads.create({
                            type: config.developer ? ChannelType.PublicThread : ChannelType.PrivateThread,
                            name: 'sbs-' + user.name.toLowerCase() + "-links",
                            autoArchiveDuration: 60,
                            reason: 'Prompt for Serious Ban Report links + files. Generated by ' + user.id,
                        }).then(thread => {
                            cache[user.identity.id].thread = thread;
                            thread.members.add(interaction.member).then(() => {
                                const overview = new EmbedBuilder()
                                    .setTitle("Add Archive Entry Overview")
                                    .setDescription("Here's what we have so far!")
                                    .setColor(0x772ce8)
                                    .addFields(
                                        {
                                            name: "Offense",
                                            value: codeBlock(entry.offense),
                                        },
                                        {
                                            name: "Description",
                                            value: codeBlock(entry.description),
                                        }
                                    )
        
                                    if (resolvable !== "")
                                        overview.addFields({
                                            name: "Resolved Users",
                                            value: codeBlock(resolvable),
                                        });
                                    if (unresolvable !== "")
                                        overview.addFields({
                                            name: "Unresolved Users",
                                            value: codeBlock(unresolvable),
                                        });

                                const embed = new EmbedBuilder()
                                    .setTitle("Add related links, images, or files!")
                                    .setDescription("Utilize Discord's upload file feature or type links to upload files to this archive submission.")
                                    .setColor(0xa970ff);

                                const submit = new ButtonBuilder()
                                    .setCustomId("submit-archive")
                                    .setLabel("Submit")
                                    .setStyle(ButtonStyle.Success);

                                const row = new ActionRowBuilder()
                                    .addComponents(submit);

                                thread.send({embeds: [overview, embed], components: [row]}).then(message => {
                                    const continueEmbed = new EmbedBuilder()
                                        .setTitle("Add files, images, and URLs!")
                                        .setDescription("We've created a new thread to add documents!\n\nVisit it [here](" + message.url + ").")
                                        .setFooter({text: "Information message. This embed will expire in 20 seconds.", iconURL: "https://tms.to/assets/images/logos/logo.webp"});
                                    interaction.reply({embeds: [continueEmbed]}).then(() => {
                                        setTimeout(() => {
                                            try {
                                                interaction.deleteReply();
                                            } catch (err) {
                                                global.api.Logger.warning(err);
                                            }
                                        }, 20000);
                                    });
                                }, err => {
                                    global.api.Logger.warning(err);
                                    thread.delete("Failed to send starting message.");
                                });
                            }, err => {
                                global.api.Logger.warning(err);
                                thread.delete("Failed to add member to thread.");
                                interaction.reply("Failed to add member to thread.");
                            });
                        }, err => {
                            global.api.Logger.warning(err);
                            interaction.reply("Unable to create a thread in this channel.");
                        });
                    } else {
                        interaction.reply({content: "Lost user data. This may have been due to an unexpected restart of ModBot. Please retry", ephemeral: true});
                    }
                } else {
                    interaction.reply({content: "Your account isn't properly linked to TMS. Contact <@267380687345025025>", ephemeral: true});
                }
            }, error => {
                interaction.reply({content: "Error: " + error, ephemeral: true});
            })
            
        }
    }
};

module.exports = listener;