name: Notify Discord on Version Tag Push

on:
  push:
    tags:
      - 'v*'

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to access all tags and history

      - name: Get previous tag
        id: prev_tag
        run: |
          PREV_TAG=$(git tag --sort=-creatordate | grep '^v' | grep -v ${{ github.ref_name }} | head -n 1 || echo "")
          echo "Previous tag: $PREV_TAG"
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: Get commit log between tags
        id: commit_log
        run: |
          RANGE="${{ steps.prev_tag.outputs.prev_tag }}..${GITHUB_REF_NAME}"
          if [ -z "${{ steps.prev_tag.outputs.prev_tag }}" ]; then
            RANGE="${GITHUB_REF_NAME}"
          fi
          echo "RANGE: $RANGE"

          # Generate commit log into a variable
          COMMITS=$(git log $RANGE --pretty=format:'- %s (%an)')

          # Save it as an output
          COMMITS="${COMMITS//'%'/'%25'}"
          COMMITS="${COMMITS//$'\n'/'%0A'}"
          COMMITS="${COMMITS//$'\r'/'%0D'}"
          echo "commits=$COMMITS" >> $GITHUB_OUTPUT

      - name: Post to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          VERSION="${GITHUB_REF_NAME#refs/tags/}"
          COMMITS="${{ steps.commit_log.outputs.commits }}"
          PAYLOAD=$(jq -n \
            --arg username "ModBot Release" \
            --arg avatar_url "https://cdn.modsquad.tools/assets/images/logo.webp" \
            --arg content "**📦 New Release: \`$VERSION\`**\n\n$COMMITS" \
            '{username: $username, avatar_url: $avatar_url, content: $content}')
          curl -X POST -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               "$DISCORD_WEBHOOK_URL"
      
